### ISSUE TITLE
Health Percent UI Problem 血條UI的問題

### ISSUE THREAD

**Issue by Kevinkang0211** [opp1opp1/Seminar-in-information-system-management-NCUE109-#4]
Some HP UI of enemy can't show normally according to its HP
----------------------------------------------------------------------------
某些敵人的血條動畫無法根據血量去顯示出來，而且Type1的敵人顯示都正常，不知道是因為Panel的問題還是腳本的問題...

**Comment by opp1opp1** [comment]
沒人回你可撥

**Comment by opp1opp1** [comment]
調完還要我幫你關問題啊
